---
# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
default_stages: [commit]
default_language_version:
  python: python3
repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.0
    hooks:
      - id: style-files
        name: Style code with `styler`
        args: [--style_pkg=styler, --style_fun=tidyverse_style,
              --cache-root=styler]
      - id: roxygenize
        name: Regenerate package documentation
        additional_dependencies:
          - rtables
          - broom
          - car
          - checkmate
          - cowplot
          - dplyr
          - emmeans
          - forcats
          - formatters
          - ggplot2
          - grid
          - gridExtra
          - gtable
          - labeling
          - lifecycle
          - magrittr
          - MASS
          - methods
          - Rdpack
          - rlang
          - scales
          - stats
          - survival
          - tibble
          - tidyr
          - utils
      - id: spell-check
        name: Check spelling with `spelling`
        exclude: >
          (?x)^(
          .*\.[rR]|
          .*\.css|
          .*\.jpg|
          .*\.js|
          .*\.png|
          .*\.py|
          .*\.RData|
          .*\.Rds|
          .*\.rds|
          .*\.Rproj|
          .*\.sh|
          .*\.svg|
          .*\.xml|
          (.*/|)\_pkgdown.y[a]?ml|
          (.*/|)\.gitignore|
          (.*/|)\.gitlab-ci\.y[a]?ml|
          (.*/|)\.lintr|
          (.*/|)\.pre-commit-.*|
          (.*/|)\.Rbuildignore|
          (.*/|)\.Renviron|
          (.*/|)\.Rprofile|
          (.*/|)CODEOWNERS|
          (.*/|)DESCRIPTION|
          (.*/|)LICENSE|
          (.*/|)NAMESPACE|
          (.*/|)staged_dependencies\.y[a]?ml|
          (.*/|)WORDLIST|
          \.github/.*\.y[a]?ml|
          data/.*
          )$
