---
title: "Design: Laboratory Test Results with Highest NCI CTCAE Grade Post-Baseline (LBT07)"
author: "Heng Wang"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Design of LBT07}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svg"
)
```

```{r data, results = "asis", eval = TRUE}

library(random.cdisc.data)
library(dplyr)
adsl <- radsl(cached = TRUE)
adlb <- radlb(cached = TRUE) 
adlb_f <- adlb %>% 
  dplyr::filter(!AVISIT %in% c("SCREENING", "BASELINE")) %>%
  dplyr::mutate(
    ATOXGR = as.numeric(as.character(ATOXGR)),
    WGRLOFL = case_when(WGRLOFL == "Y" ~ TRUE, TRUE ~ FALSE),
    WGRHIFL = case_when(WGRHIFL == "Y" ~ TRUE, TRUE ~ FALSE)
  ) 
```


## Elementary function: `h_abnormal_by_worst_grade`
```{r}
library(utils.nest)
library(rtables)
library(assertthat)
library(tern)

# Elementary function: take one abnormal and grade flag
h_abnormal_by_worst_grade <- function(df, 
                                      .var = "ATOXGR",
                                      abnormal = c("low", "high"),
                                      variables = list(id = "USUBJID", worst_grade_flag = "WGRLOFL")) {
  abnormal <- match.arg(abnormal)
  assertthat::assert_that(
    is.string(.var),
    is.string(abnormal),
    is.list(variables),
    all(names(variables) %in% c("id", "worst_grade_flag")),
    is_df_with_variables(df, c(aval = .var, variables)),
    is_numeric_vector(df[[.var]]),  
    is_logical_vector(df[[variables$worst_grade_flag]]),
    is_character_or_factor(df[[variables$id]])
  )
  
  df <- df[!is.na(df[[.var]]), ]
  anl <- data.frame(
    id = df[[variables$id]],
    grade = df[[.var]] ,
    flag = df[[variables$worst_grade_flag]], 
    stringsAsFactors = FALSE
  )
  # Denominator is number of patients with at least one valid measurement during treatment
  n <- length(unique(anl$id))
  # Numerator is number of patients with worst high grade (grade 1 to 5) or low grade (grade -1 to -5)
  if (abnormal == "low"){
    anl_abn <- anl[anl$flag & anl$grade < 0, , drop = FALSE] 
    grades <- setNames(-(1:5), as.character(1:5))
  } else if (abnormal == "high"){
    anl_abn <- anl[anl$flag & anl$grade > 0, , drop = FALSE] 
    grades <- setNames(1:5, as.character(1:5))
  }
  
  by_grade <- lapply(grades, function(i) {
    num <- length(unique(anl_abn[anl_abn$grade == i, "id", drop = TRUE])) 
    c(num, num/n)  
  })
  # Numerator for "Any" is number of patients with at least one high/low abnormality
  any_grade_num <- length(unique(anl_abn[anl_abn$grade != 0, "id", drop = TRUE])) 
  
  c(by_grade, list("Any" = c(any_grade_num, any_grade_num/n)))
}

# Examples
h_abnormal_by_worst_grade(
  df = adlb_f %>% filter(ARMCD == "ARM A" & PARAMCD == "CRP"),
  .var = "ATOXGR",
  abnormal = "low",
  variables = list(id = "USUBJID", worst_grade_flag = "WGRLOFL")
) 
h_abnormal_by_worst_grade(
  df = adlb_f %>% filter(ARMCD == "ARM A" & PARAMCD == "CRP"),
  .var = "ATOXGR",
  abnormal = "high",
  variables = list(id = "USUBJID", worst_grade_flag = "WGRHIFL")
)
 
```

## Stats function: `s_abnormal_by_worst_grade`
```{r}

s_abnormal_by_worst_grade <- function(df, 
                                      .var, 
                                      abnormal = c("Low" = "low", "High" = "high"),
                                      variables = list(
                                        id = "USUBJID",
                                        worst_grade_flags = c("Low" = "WGRLOFL", "High" = "WGRHIFL")
                                      )) {
  assert_that(
    !is.null(names(abnormal)),
    !is.null(names(variables$worst_grade_flag)),
    identical(names(abnormal), names(variables$worst_grade_flag))
  )
  
  result <- Map(function(abn, flag) {
    h_abnormal_by_worst_grade(
      df = df,
      .var = .var,
      abnormal = abn,
      variables = list(
        id = variables$id,
        worst_grade_flag = flag
      ) 
    )
  }, abnormal, variables$worst_grade_flag)
  
  lbl_result <- Map(function(x, nm) { 
     list(
       section_label = with_label("", nm),
       count_fraction = x
     )   
  }, x = result, nm = names(result))
  tern:::flatten_list(lbl_result)
}

# Examples
s_abnormal_by_worst_grade(
  df = adlb_f %>% filter(ARMCD == "ARM A" & PARAMCD == "CRP"),
  .var = "ATOXGR",
  abnormal = c(High = "high"),
  variables = list(id = "USUBJID", worst_grade_flag = c(High = "WGRHIFL")) 
)

s_abnormal_by_worst_grade(
  df = adlb_f %>% filter(ARMCD == "ARM A" & PARAMCD == "CRP"),
  .var = "ATOXGR",
  abnormal = c(Low = "low", High = "high"),
  variables = list(id = "USUBJID", worst_grade_flag = c(Low = "WGRLOFL", High = "WGRHIFL"))
)
```

## Analyze function: `abnormal_by_worst_grade`
```{r}
abnormal_by_worst_grade <- function(lyt,
                                    vars,
                                    ...) {
  a_abnormal_by_worst_grade <- tern:::format_wrap_df(
    s_abnormal_by_worst_grade, 
    indent_mods = c(section_label = 0L, count_fraction = 2L),
    formats = c(section_label = "xx", count_fraction = format_count_fraction)
  )
  analyze(
    lyt,
    vars,
    afun = a_abnormal_by_worst_grade,
    extra_args = list(...)
  )
}

# Example
basic_table() %>%
  split_cols_by("ARMCD") %>%
  split_rows_by("PARAMCD") %>%  
  abnormal_by_worst_grade(
    vars = "ATOXGR",
    abnormal = c(Low = "low", High = "high"),
    variables = list(id = "USUBJID", worst_grade_flag = c(Low = "WGRLOFL", High = "WGRHIFL")) 
  ) %>%
  build_table(df = adlb_f) 

```

## Analyze function to get unique patients having at least one valid test (n):

```{r}
# Count unique id by excluding missing value from .var
h_count_unique_id <- function(df, .var, id, labelstr = "") {
  assert_that(
    is.string(.var),
    is.string(id),
    is_df_with_variables(df, list(id = id, var = .var)),
    is_character_or_factor(df[[id]])
  )
  list(n = length(unique(df[!is.na(df[[.var]]), id, drop = TRUE])))
}

count_unique_id <- function(lyt, var, id, .stats = "n", .formats = c(n = "xx")){
  c_unique_id <- make_afun(
    h_count_unique_id, 
    .stats = .stats, 
    .formats = .formats
  )
  summarize_row_groups(
    lyt = lyt,
    var = var,
    cfun = c_unique_id,
    extra_args = list(id = id)
  )
}

# Example
basic_table() %>%
  split_cols_by("ARMCD") %>%
  split_rows_by("PARAMCD") %>%
  count_unique_id(var = "ATOXGR", id = "USUBJID" ) %>%   
  abnormal_by_worst_grade(
    vars = "ATOXGR",
    abnormal = c(Low = "low", High = "high"),
    variables = list(id = "USUBJID", worst_grade_flag = c(Low = "WGRLOFL", High = "WGRHIFL")) 
  ) %>%
  build_table(df = adlb_f) 
```

 
