---
title: "Design for Liver Laboratory Tests by Time on Treatment - Patients with Elevated Post-Baseline AST or ALT Levels (with respect to baseline) (LBT12_BL)"
author: "Rosemary Li"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Design of LBT12_BL}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svg"
)
```

Configuration
=============

```{r setup}
library(dplyr)
library(tern)

packageVersion("tern")
packageVersion("rtables")
```

Data for examples
=================

```{r data, results = "asis", eval = TRUE}

adhy <- haven::read_sas(data_file = "/home/rstudio/nest_projects/tern/temp/adhy.sas7bdat")
adsl <- haven::read_sas(data_file = "/home/rstudio/nest_projects/tern/temp/adsl.sas7bdat")

# Used for population N's shown in table header.
adsl <- adsl %>% filter(SAFFL == "Y")

# Select LBT12 parameters
anl <- adhy %>%
  filter(SAFFL == "Y") %>%
  filter(PARAMCD %in% c('ASTPBASE', 'ALTPBASE', 'ALTASTPB') & AVISIT == "POST-BASELINE") %>%
  mutate(ARM_AVALC = case_when(
    AVALC == "Y" & ACTARMCD == "A" ~ "ARM A",
    AVALC == "Y" & ACTARMCD == "B" ~ "ARM B",
    AVALC == "Y" & ACTARMCD == "C" ~ "ARM C"
  ))

anl <- df_explicit_na(anl) %>%
  mutate(
    TITLE = "First Elevated Result Occurring During"
  )
```

Layout
======

```{r}
result <- basic_table() %>%
  split_cols_by("TITLE") %>%
  split_cols_by("APERIODC") %>%
  split_rows_by("PARAM") %>%
  split_rows_by("ACTARM", split_fun = drop_split_levels, child_labels = "hidden") %>% 
  count_occurrences(vars = "ARM_AVALC", denom = "n", .stats = "fraction") %>%
  build_table(anl)

criteria_fun <- function(tr) {
  row_label <- obj_label(tr)
  ifelse(row_label == "<Missing>", TRUE, FALSE)
}
result <- result %>% trim_rows(criteria = criteria_fun)

result
```

For rows with 0 count, the above way will now show that arm. However this should be solved when new split function that can produce a map and show specifically what rows should be included in the layout.
