---
title: "Design for helper function to create layout map for lbt07"
author: "Rosemary Li"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    theme: journal
    highlight: zenburn
vignette: >
  %\VignetteIndexEntry{Design of LBT04}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svg"
)
```

Configuration
=============

```{r setup}
library(rtables)
library(tern)
library(dplyr)
library(assertthat)

packageVersion("tern")
packageVersion("rtables")
```

Introduction
=============

LBT07 used the function `count_abnormal_by_worst_grade` which will need a map for layout.

Design
=============

Maybe the function can get different `method` so that map for different templates can be created accordingly.

```{r eval=FALSE}
ext_ncictc4 <- haven::read_sas("metadata/ext_ncictc4.sas7bdat")
ext_ncictc4 <- usethis::use_data(ext_ncictc4)
```


```{r}
h_map_for_count_abnormal_by_worst_grade <- function(
  df,
  variables = list(anl = "GRADE_ANL", split_rows = c("PARAM", "GRADE_DIR")),
  abnormal = list(low = "LOW", high = "HIGH"),
  na_level = "<Missing>"
) {
  assert_that(
    is_df_with_variables(df, variables),
    "anl" %in% names(variables),
    "split_rows" %in% names(variables),
    "PARAM" %in% unlist(variables) || "PARAMCD" %in% unlist(variables),
    is_df_with_factors(df, variables),
    any(unlist(abnormal) %in% levels(df[[variables$split_rows[-1]]]))
  )
  data("ext_ncictc4")
  ext_ncictc4 <- ext_ncictc4[c("PARAMCD", "RESULT")]
  ext_ncictc4 <- ext_ncictc4[ext_ncictc4[["PARAMCD"]] %in% unique(df[["PARAMCD"]]), ]
  ext_ncictc4[[variables$split_rows[-1]]] <- na_level
  ext_ncictc4[ext_ncictc4[["RESULT"]] %in% c("1", "2", "3", "4"), ][[variables$split_rows[-1]]] <- abnormal$high
  ext_ncictc4[ext_ncictc4[["RESULT"]] %in% c("-1", "-2", "-3", "-4"), ][[variables$split_rows[-1]]] <- abnormal$low
  ext_ncictc4 <- unique(ext_ncictc4[ext_ncictc4[[variables$split_rows[-1]]] != na_level, ][c("PARAMCD", variables$split_rows[-1])]) #nolint

  if ("PARAMCD" %in% variables$split_rows) {
    map <- unique(df[c(variables$split_rows, variables$anl)])
    map <- map[map[[variables$split_rows[-1]]] %in% unlist(abnormal),]
    map <- merge(map, ext_ncictc4, all = TRUE)
  } else {
    map <- unique(df[c(variables$split_rows, "PARAMCD", variables$anl)])
    map <- map[map[[variables$split_rows[-1]]] %in% unlist(abnormal),]
    ext_ncictc4 <- merge(ext_ncictc4, param_map)
    map <- merge(map, ext_ncictc4, all = TRUE)
  }

  map <- map[c(variables$split_rows, variables$anl)]
  map <- data.frame(lapply(map, as.character), stringsAsFactors = FALSE)
}
```

STREAM data test
=============

```{r}
adsl <- ADSL %>% filter(SAFFL == "Y") %>% df_explicit_na()
adlb <- ADLB %>% df_explicit_na() %>%
  filter(ONTRTFL == "Y" & ATOXGR != "<Missing>" & PARCAT2 == "SI" & SAFFL == "Y")
adlb_f <- adlb %>%
  mutate(
    GRADE_DIR = factor(case_when(
      ATOXGR %in% c("-1", "-2", "-3") ~ "LOW",
      ATOXGR == "0" ~ "ZERO",
      ATOXGR %in% c("1", "2", "3") ~ "HIGH"),
      levels = c("LOW", "ZERO", "HIGH")),
    GRADE_ANL = fct_relevel(
      fct_recode(ATOXGR,
                 `1` = "-1", `2` = "-2", `3` = "-3"),
      c("0", "1", "2", "3")
    )
  ) %>%
  filter(WGRLOFL == "Y" | WGRHIFL == "Y") %>%
  droplevels()
levels(adlb_f$GRADE_ANL) <- c("0", "1", "2", "3", "Any")

map <- adlb_f %>% select(PARAMCD, GRADE_DIR, GRADE_ANL) %>% unique() %>% filter(GRADE_DIR != "ZERO")
map <- ext_ncictc4 %>% left_join(map, by = c("PARAMCD", "GRADE_DIR")) %>% unique() %>% arrange(PARAMCD)
map <- map %>% mutate(GRADE_ANL = ifelse(is.na(GRADE_ANL), "Any", as.character(GRADE_ANL)))

basic_table() %>%
  split_cols_by("ARMCD") %>%
  add_colcounts() %>%
  split_rows_by("PARAMCD") %>%
  summarize_num_patients(
    var = "USUBJID",
    required = "GRADE_DIR",
    .stats = "unique_count"
  ) %>% 
  split_rows_by("GRADE_DIR", split_fun = trim_levels_to_map(map)) %>%
  count_abnormal_by_worst_grade(
    var = "GRADE_ANL",
    variables = list(id = "USUBJID", param  = "PARAMCD", grade_dir = "GRADE_DIR")
  ) %>%
  build_table(df = adlb_f, alt_counts_df = adsl)

```



Unit Tests
=============
```{r}
df <- data.frame(
  USUBJID = c(rep("1", 4), rep("2", 4), rep("3", 4)),
  AVISIT = c(
    rep("WEEK 1", 2), rep("WEEK 2", 2), rep("WEEK 1", 2), rep("WEEK 2", 2), rep("WEEK 1", 2), rep("WEEK 2", 2)
  ),
  PARAM = rep(c("ALT", "CPR"), 6),
  ANRIND = c("NORMAL", "NORMAL", "LOW", "HIGH", "LOW", "LOW", "HIGH", "HIGH", rep("NORMAL", 4))
)
df$ANRIND <- factor(df$ANRIND, levels = c("LOW", "HIGH", "NORMAL")) #nolint
```
