---
title: "Design for Liver Laboratory Tests - Patients with Elevated Post-Baseline AST or ALT Levels at Two Consecutive Visits (with respect to ULN) (LBT10)"
author: "Wojciech Wojciak"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Design of LBT10}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svg"
)
```

Configuration
=============

```{r setup}
library(dplyr)
library(tern)

packageVersion("tern")
packageVersion("rtables")
```

Data for examples
=================

```{r data, results = "asis", eval = TRUE}

adhy <- haven::read_sas(data_file = "adhy.sas7bdat")
adsl <- haven::read_sas(data_file = "adsl.sas7bdat")

# Used for population N's shown in table header.
adsl <- adsl %>% dplyr::filter(SAFFL == "Y")

# Select LBT10 parameters
anl <- adhy %>%
  dplyr::filter(SAFFL == "Y") %>%
  dplyr::filter(PARAMCD %in% c("BL2AL2CU", "BL2AS2CU", "BG2AL2CU", "BG2AS2CU",
                        "B2A2L2CU", "B2A2S2CU", "B2A5L2CU", "B2A5S2CU"))

# Create TBILI_CAT - this is needed so we get the right nesting in the table.
anl <- anl %>%
  dplyr::mutate(
    TBILI_CAT = factor(dplyr::case_when(
      PARAMCD %in% c("BL2AL2CU", "BL2AS2CU") ~ "Total Bilirubin <= 2xULN",
      PARAMCD %in% c("BG2AL2CU", "BG2AS2CU") ~ "Total Bilirubin > 2xULN",
      PARAMCD %in% c("B2A2L2CU", "B2A2S2CU") ~ "Total Bilirubin > 2xULN and Alkaline Phosphatase <= 2xULN",
      PARAMCD %in% c("B2A5L2CU", "B2A5S2CU") ~ "Total Bilirubin > 2xULN and Alkaline Phosphatase <= 5xULN"
    ))
  )

# Create ALTAST_IND - this will be the labels for the ALT/AST categories displayed in the table.
anl <- anl %>%
  dplyr::mutate(
    ALTAST_IND = factor(dplyr::case_when(
      PARAMCD %in% c("BL2AL2CU", "BG2AL2CU", "B2A2L2CU", "B2A5L2CU") & AVALC == "Y" ~ "ALT >3xULN at 2 Visits",
      PARAMCD %in% c("BL2AS2CU", "BG2AS2CU", "B2A2S2CU", "B2A5S2CU") & AVALC == "Y" ~ "AST >3xULN at 2 Visits",
      TRUE ~ "Criteria not met"
    ))
  )

anl <- df_explicit_na(anl)
```

Layout
======

```{r layout}

tbl <- basic_table() %>%
  split_cols_by("ARM") %>%
  add_colcounts() %>%
  split_rows_by("TBILI_CAT") %>%
  # below split helps us get the right denominator between ALT/AST categories but it's hidden
  split_rows_by("PARAM", child_labels = "hidden", split_fun = drop_split_levels) %>%
  count_occurrences("ALTAST_IND", .stats = "fraction", denom = "n") %>%
  append_topleft("Liver Laboratory Test Criterion") %>%
  build_table(anl, alt_counts_df = adsl)

tbl

# Filter out AVALC=N (Criteria not met) records.
criteria_fun <- function(tr) {
  row_label <- obj_label(tr)
  ifelse(row_label == "Criteria not met", TRUE, FALSE)
}

result <- tbl %>% trim_rows(criteria = criteria_fun)
result
```
