---
title: "Design for h_append_grade_group refactoring"
author: "Rosemary Li"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    theme: journal
    highlight: zenburn
vignette: >
  %\VignetteIndexEntry{Design of AET04}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svg"
)
```

Configuration
=============

```{r setup}
library(scda)
library(rtables)
library(tern)
library(assertthat)
library(dplyr)

packageVersion("tern")
packageVersion("rtables")
```

### h_append_grade_groups

Here the main change is that we no longer "fill-in" all the `grade_groups`.
```{r, sfun}
h_append_grade_groups <- function(grade_groups, refs, remove_single = TRUE) {

  assert_that(
    is.list(grade_groups),
    is.list(refs)
  )

  refs_orig <- refs

  elements <- unique(unlist(grade_groups))

  ### compute sums in groups
  grp_sum <- lapply(grade_groups, function(i) do.call(sum, refs[i]))
  if (!all_elements_in_ref(elements, names(refs))) {
    padding_el <- setdiff(elements, names(refs))
    refs[padding_el] <- 0
  }
  result <- c(grp_sum, refs)

  ### order result while keeping grade_groups's ordering
  ordr <- grade_groups

  # elements of any-grade group (if any) will be moved to the end
  is_any <- sapply(grade_groups, setequal, y = names(refs))
  ordr[is_any] <- list(character(0)) # hide elements under any-grade group

  # groups-elements combined sequence
  ordr <- c(lapply(names(ordr), function(g) c(g, ordr[[g]])), recursive = TRUE, use.names = FALSE)
  ordr <- ordr[!duplicated(ordr)]

  # append remaining elements (if any)
  ordr <- union(ordr, unlist(grade_groups[is_any])) # from any-grade group
  ordr <- union(ordr, names(refs)) # from refs

  # remove elements of single-element groups, if any
  if (remove_single) {
    is_single <- sapply(grade_groups, length) == 1L
    ordr <- setdiff(ordr, unlist(grade_groups[is_single]))
  }

  # apply the order
  result <- result[ordr]

  # Remove groups without any elements in the original refs
  # Note: is't OK if groups have 0 value
  keep_grp <- vapply(grade_groups, function(x, rf) {
    any(x %in% rf)
  }, rf = names(refs_orig), logical(1))

  keep_el <- names(result) %in% names(refs_orig) | names(result) %in% names(keep_grp)[keep_grp]
  result <- result[keep_el]

  result
}
```

### test out new helper `h_append_grade_groups` 
```{r}
grade_groups <- list(
  "Any Grade" = as.character(1:5),
  "Grade 1-2" = c("1", "2"),
  "Grade 3-4" = c("3", "4")
)

h_append_grade_groups(grade_groups, refs = list("1" = 10, "2" = 20))

# This case needs to work to avoid tabulation error when some columns do not
# include a specific grade and there is a mismatch in the number of elements
# returned across columns.
h_append_grade_groups(grade_groups, refs = list("1" = 10, "2" = 0))

# This case adds the Grade 3-4 group even when total count is 0.
h_append_grade_groups(grade_groups, refs = list("1" = 10, "2" = 5, "3" = 0))
```

# No changes needed in the s_*, a_* or layout functions
```{r}
s_count_occurrences_by_grade <- function(df,
                                         .var,
                                         .N_col, #nolint
                                         id = "USUBJID",
                                         grade_groups = list(),
                                         remove_single = TRUE,
                                         labelstr = "") {

  assert_that(
    is_df_with_variables(df, list(grade = .var, id = id)),
    is_valid_factor(df[[.var]])
  )

  if (nrow(df) < 1) {

    grade_levels <- levels(df[[.var]])
    l_count <- as.list(rep(0, length(grade_levels)))
    names(l_count) <- grade_levels

  } else {

    assert_that(
      is_nonnegative_count(.N_col),
      noNA(df[[id]]),
      is_valid_character(df[[id]]) || is_valid_factor(df[[id]])
    )

    id <- df[[id]]
    grade <- df[[.var]]

    if (!is.ordered(grade)) {

      grade_lbl <- obj_label(grade)
      grade <- with_label(factor(grade, levels = levels(grade), ordered = TRUE), grade_lbl)

    }

    df_max <- aggregate(grade ~ id, FUN = max, drop = FALSE)
    l_count <- as.list(table(df_max$grade))
  }

  if (length(grade_groups) > 0) {
    l_count <- h_append_grade_groups(grade_groups, l_count, remove_single)
  }

  l_count_fraction <- lapply(l_count, function(i, denom) c(i, i / denom), denom = .N_col)

  list(
    count_fraction = l_count_fraction
  )

}

a_count_occurrences_by_grade <- make_afun(
  s_count_occurrences_by_grade,
  .formats = c("count_fraction" = format_count_fraction)
)

count_occurrences_by_grade <- function(lyt,
                                       var,
                                       var_labels = var,
                                       show_labels = "default",
                                       ...,
                                       table_names = var,
                                       .stats = NULL,
                                       .formats = NULL,
                                       .indent_mods = NULL,
                                       .labels = NULL) {
  afun <- make_afun(
    a_count_occurrences_by_grade,
    .stats = .stats,
    .formats = .formats,
    .indent_mods = .indent_mods,
    .ungroup_stats = "count_fraction"
  )

  analyze(
    lyt = lyt,
    vars = var,
    var_labels = var_labels,
    show_labels = show_labels,
    afun = afun,
    table_names = table_names,
    extra_args = list(...)
  )
}

summarize_occurrences_by_grade <- function(lyt,
                                           var,
                                           ...,
                                           .stats = NULL,
                                           .formats = NULL,
                                           .indent_mods = NULL,
                                           .labels = NULL) {
  cfun <- make_afun(
    a_count_occurrences_by_grade,
    .stats = .stats,
    .formats = .formats,
    .labels = .labels,
    .indent_mods = .indent_mods,
    .ungroup_stats = "count_fraction"
  )

  summarize_row_groups(
    lyt = lyt,
    var = var,
    cfun = cfun,
    extra_args = list(...)
  )
}
```

# Simple example

```{r}
df <- data.frame(
  USUBJID = as.character(1:30),
  ARM = factor(c(rep("ARM A", 15), rep("ARM B", 15)), levels = c("ARM A", "ARM B")),
  SOC = as.factor(rep("SOC1", 30)),
  AETOXGR = factor(c(rep(1, 10), rep(2, 20)), levels = c(1:5))
)

df_adsl <- df %>%
 select(USUBJID, ARM) %>%
 unique()

# Grades 3+ are not returned since not observed in the data
 s_count_occurrences_by_grade(
   droplevels(df),
   .N_col = 30L, # nolint
   .var = "AETOXGR",
   id = "USUBJID",
   grade_groups = grade_groups
 )
 
# Grades 3+ are not returned since not observed in the data
basic_table() %>%
   split_cols_by("ARM") %>%
   add_colcounts() %>%
   split_rows_by("SOC", split_fun = trim_levels_in_group("AETOXGR")) %>%
   count_occurrences_by_grade(
     var = "AETOXGR",
     grade_groups = grade_groups
   ) %>%
   build_table(df, alt_counts_df = df_adsl)

# Grades 3+ can be "filled-in" by changing the split function
basic_table() %>%
   split_cols_by("ARM") %>%
   add_colcounts() %>%
   split_rows_by("SOC") %>%
   count_occurrences_by_grade(
     var = "AETOXGR",
     grade_groups = grade_groups
   ) %>%
   build_table(df, alt_counts_df = df_adsl)
```

### check full AET03 layout
```{r}
adsl <- synthetic_cdisc_data("latest")$adsl
adae <- synthetic_cdisc_data("latest")$adae
```

old way
```{r}
start_time <- Sys.time()
grade_groups <- list(
  "- Any Intensity -" = c("MILD", "MODERATE", "SEVERE")
)

split_fun <- drop_split_levels

lyt <- basic_table() %>%
  split_cols_by("ACTARM") %>%
  add_colcounts() %>%
  tern::summarize_occurrences_by_grade(
    var = "AESEV",
    grade_groups = grade_groups
  ) %>%
  split_rows_by(
    "AEBODSYS",
    child_labels = "visible",
    nested = TRUE,
    indent_mod = -1L,
    split_fun = split_fun,
    label_pos = "topleft",
    split_label = obj_label(adae$AEBODSYS)
    ) %>%
  tern::summarize_occurrences_by_grade(
    var = "AESEV",
    grade_groups = grade_groups
  ) %>%
  split_rows_by(
    "AEDECOD",
    child_labels = "visible",
    nested = TRUE,
    indent_mod = -1L,
    split_fun = split_fun,
    label_pos = "topleft",
    split_label = obj_label(adae$AEDECOD)
    ) %>%
  tern::summarize_num_patients(
    var = "USUBJID",
    .stats = "unique",
    .labels = c("- Any Intensity -")
  ) %>%
  tern::count_occurrences_by_grade(
    var = "AESEV",
    .indent_mods = -1L
    ) %>%
  append_varlabels(adae, "AESEV", indent = 2L)


result <- lyt %>%
  build_table(
    adae,
    alt_counts_df = adsl
    ) %>%
  trim_rows() %>%
  sort_at_path(
    path = "AEBODSYS",
    scorefun = cont_n_allcols,
    decreasing = TRUE
  ) %>%
  sort_at_path(
    path = c("AEBODSYS", "*", "AEDECOD"),
    scorefun = cont_n_allcols,
    decreasing = TRUE
  )

end_time <- Sys.time()
print(end_time - start_time)
```

new way
```{r}
start_time <- Sys.time()
grade_groups <- list(
  "- Any Intensity -" = c("MILD", "MODERATE", "SEVERE")
)

split_fun <- trim_levels_in_group("AESEV")

lyt <- basic_table() %>%
  split_cols_by("ACTARM") %>%
  add_colcounts() %>%
  summarize_occurrences_by_grade(
    var = "AESEV",
    grade_groups = grade_groups
  ) %>%
  split_rows_by(
    "AEBODSYS",
    child_labels = "visible",
    nested = TRUE,
    indent_mod = -1L,
    split_fun = split_fun,
    label_pos = "topleft",
    split_label = obj_label(adae$AEBODSYS)
    ) %>%
  summarize_occurrences_by_grade(
    var = "AESEV",
    grade_groups = grade_groups
  ) %>%
  split_rows_by(
    "AEDECOD",
    child_labels = "visible",
    nested = TRUE,
    indent_mod = -1L,
    split_fun = split_fun,
    label_pos = "topleft",
    split_label = obj_label(adae$AEDECOD)
    ) %>%
  summarize_num_patients(
    var = "USUBJID",
    .stats = "unique",
    .labels = c("- Any Intensity -")
  ) %>%
  count_occurrences_by_grade(
    var = "AESEV",
    .indent_mods = -1L
    ) %>%
  append_varlabels(adae, "AESEV", indent = 2L)


# Note no longer need trim_rows()
result <- lyt %>%
  build_table(
    adae,
    alt_counts_df = adsl
    ) %>%
  sort_at_path(
    path = "AEBODSYS",
    scorefun = cont_n_allcols,
    decreasing = TRUE
  ) %>%
  sort_at_path(
    path = c("AEBODSYS", "*", "AEDECOD"),
    scorefun = cont_n_allcols,
    decreasing = TRUE
  )

end_time <- Sys.time()
print(end_time - start_time)
```


### check full AET04 layout

old way
```{r}
start_time <- Sys.time()
gr_grp <-  list(
  "- Any Grade -" = c("1", "2", "3", "4", "5"),
  "Grade 1-2" = c("1", "2"),
  "Grade 3-4" = c("3", "4"),
  "Grade 5" = "5"
)

split_fun <- drop_split_levels

lyt <- basic_table() %>%
  split_cols_by("ACTARM") %>%
  add_colcounts() %>%
  tern::summarize_occurrences_by_grade(
    var = "AETOXGR",
    grade_groups = gr_grp
  ) %>%
  split_rows_by(
    "AEBODSYS",
    child_labels = "visible", 
    nested = TRUE, 
    indent_mod = -1L,
    split_fun = split_fun,
    label_pos = "topleft",
    split_label = obj_label(adae$AEBODSYS)
  ) %>%
  tern::summarize_occurrences_by_grade(
    var = "AETOXGR",
    grade_groups = gr_grp
  ) %>%
  split_rows_by(
    "AEDECOD", 
    child_labels = "visible", 
    nested = TRUE, 
    indent_mod = -1L,
    split_fun = split_fun,
    label_pos = "topleft",
    split_label = obj_label(adae$AEDECOD)
  ) %>%
  tern::summarize_num_patients(
    var = "USUBJID",
    .stats = "unique",
    .labels = "- Any Grade -"
  ) %>%
  tern::count_occurrences_by_grade(
    var = "AETOXGR",
    grade_groups = gr_grp[-1],
    .indent_mods = -1L
  ) %>%
  append_varlabels(adae, "AETOXGR", indent = 2L)

result <- lyt %>%
  build_table(adae, alt_counts_df = adsl) %>%
  trim_rows() %>%
  sort_at_path(
    path = "AEBODSYS",
    scorefun = cont_n_allcols,
    decreasing = TRUE
  ) %>%
  sort_at_path(
    path = c("AEBODSYS", "*", "AEDECOD"),
    scorefun = cont_n_allcols,
    decreasing = TRUE
  )
end_time <- Sys.time()
print(end_time - start_time)
```

new way
```{r}
start_time <- Sys.time()
gr_grp <-  list(
  "- Any Grade -" = c("1", "2", "3", "4", "5"),
  "Grade 1-2" = c("1", "2"),
  "Grade 3-4" = c("3", "4"),
  "Grade 5" = "5"
)

split_fun <- trim_levels_in_group("AETOXGR")

lyt <- basic_table() %>%
  split_cols_by("ACTARM") %>%
  add_colcounts() %>%
  summarize_occurrences_by_grade(
    var = "AETOXGR",
    grade_groups = gr_grp
  ) %>%
  split_rows_by(
    "AEBODSYS", 
    child_labels = "visible", 
    nested = TRUE, 
    indent_mod = -1L,
    split_fun = split_fun,
    label_pos = "topleft",
    split_label = obj_label(adae$AEBODSYS)
  ) %>%
  summarize_occurrences_by_grade(
    var = "AETOXGR",
    grade_groups = gr_grp
  ) %>%
  split_rows_by(
    "AEDECOD", 
    child_labels = "visible", 
    nested = TRUE, 
    indent_mod = -1L,
    split_fun = split_fun,
    label_pos = "topleft",
    split_label = obj_label(adae$AEDECOD)
  ) %>%
  summarize_num_patients(
    var = "USUBJID",
    .stats = "unique",
    .labels = "- Any Grade -"
  ) %>%
  count_occurrences_by_grade(
    var = "AETOXGR",
    grade_groups = gr_grp[-1],
    .indent_mods = -1L
  ) %>%
  append_varlabels(adae, "AETOXGR", indent = 2L)

# Note no longer need trim rows
result <- lyt %>%
  build_table(adae, alt_counts_df = adsl) %>%
  sort_at_path(
    path = "AEBODSYS",
    scorefun = cont_n_allcols,
    decreasing = TRUE
  ) %>%
  sort_at_path(
    path = c("AEBODSYS", "*", "AEDECOD"),
    scorefun = cont_n_allcols,
    decreasing = TRUE
  )

end_time <- Sys.time()
print(end_time - start_time)
```
