---
title: "Design: Deaths (DTH01)"
author: "Saibah Chohan"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: true
    theme: journal
    highlight: zenburn
vignette: >
  %\VignetteIndexEntry{design_dth01}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: ../inst/REFERENCES.bib

---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svg"
)
```

Configuration
=============


```{r setup}
library(random.cdisc.data)
library(assertthat)
library(rtables)
library(dplyr)
library(utils)
library(utils.nest)
library(tern)

packageVersion("rtables")

```

# Set up data

```{r data}
adsl <- radsl(cached = TRUE)
set.seed(36857, kind = "Mersenne-Twister")

# create DTHCAT
# nolint start
adsl$DTHCAT <- NA
adsl$DTHCAT[!is.na(adsl$DTHDT)] <- sample(
  x = c("ADVERSE EVENT", "PROGRESSIVE DISEASE", "OTHER"),
  size = sum(!is.na(adsl$DTHDT)),
  replace = TRUE, prob = c(.5, .3, .2)
)
adsl$DTHCAT <- factor(adsl$DTHCAT, level = c("ADVERSE EVENT", "PROGRESSIVE DISEASE", "OTHER"))


#Create DTHCAUS with reasons for "Other" specified.
#Death flag variable (Y or N)
adsl <- adsl %>% mutate(DTHCAUS = ifelse(!is.na(DTHCAT) & DTHCAT == "OTHER",
                                          sample(
                                            x = c(
                                              "Post-study reporting of death",
                                              "LOST TO FOLLOW UP",
                                              "MISSING",
                                              "SUICIDE",
                                              "UNKNOWN"
                                            ),
                                            size = sum((!is.na(adsl$DTHCAT) & adsl$DTHCAT == "OTHER")),
                                            replace = TRUE, prob = c(.1, .3, .3, .2, .1)),
                                          as.character(DTHCAT)
                                          ),
                        DTHFL = ifelse(is.na(DTHDT), "N", "Y"))

adsl$DTHCAUS <- as.factor(adsl$DTHCAUS)

# Create dummy variables LDDTHELD and LDDTHGR1 as in ADSL GDSR structure
adsl <- within(
  data = adsl,
  expr = {
    TRTEDTM <- as.Date(TRTEDTM)
    DTHDT <- as.Date(DTHDT)

    DTHDT[!is.na(DTHDT)] <- {
      DTHDT[!is.na(DTHDT)] +
        round(rnorm(n = sum(!is.na(DTHDT)), mean = 30, sd = 8))
    }

    # Dummy variable LDDTHELD: Elapsed Days from Last Dose to Death.
    LDDTHELD <- as.numeric(DTHDT - TRTEDTM)

    # Dummy variable LDDTHGR1:
    # Last Dose to Death - Days Elapsed Grp 1. Categorical variable with 2 levels: "<=30" and ">30"
    LDDTHGR1 <- cut(
      LDDTHELD,
      breaks = c(
        min(LDDTHELD, na.rm = TRUE), 30, max(LDDTHELD, na.rm = TRUE)
      ), include.lowest = TRUE
    )
  }
)
# nolint end

# LDDTHGR1: Categorical variable with 2 levels: "<=30" and ">30"
levels(adsl$LDDTHGR1) <- c("<=30", ">30")
```


# Variant 1. Deaths

```{r variant 1}
# Application with default value.
tbl1 <- basic_table() %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  add_colcounts() %>%
    count_values("DTHFL", values = "Y", .labels =  c(count_fraction = "Total number of deaths"),
                                   .formats = c(count_fraction = "xx (xx.x%)"))  %>%
  summarize_vars(vars = c("DTHCAT"), var_labels = c("Primary cause of death")) %>%
  build_table(df = adsl)

tbl1
```

# Variant 2. Deaths (selecting sections to display)

```{r variant 2}

part1 <- basic_table() %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  add_colcounts() %>%
    count_values("DTHFL", values = "Y", .labels =  c(count_fraction = "Total number of deaths"),
                                   .formats = c(count_fraction = "xx (xx.x%)"))  %>%
  summarize_vars(vars = c("DTHCAT"), var_labels = c("Primary cause of death")) %>%
    build_table(df = adsl)

part2 <- basic_table() %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  add_colcounts() %>%
  split_rows_by("DTHCAT", split_fun = keep_split_levels("OTHER"), child_labels = "hidden") %>%
  summarize_vars("DTHCAUS", nested = T, .stats = "count_fraction", .indent_mods = c("count_fraction" = 4L)) %>%
  build_table(df = adsl) %>%
    prune_table()

part3 <- basic_table() %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
 add_colcounts() %>%
  summarize_vars(
    vars = "LDDTHGR1",
    var_labels = "Days from last drug administration",
    show_labels = "visible") %>%
      build_table(df = adsl)

part4 <- basic_table() %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  add_colcounts() %>%
    split_rows_by(
      "LDDTHGR1",
      split_label = "Primary cause by days from last study drug administration",
      visible_label = TRUE) %>%
  summarize_vars("DTHCAT") %>%
  build_table(df = adsl)

col_info(part2) <- col_info(part1)
col_info(part3) <- col_info(part2)
col_info(part4) <- col_info(part3)

tbl2 <- rbind(part1, part2)
tbl2 <- rbind(tbl2, part3)
tbl2 <- rbind(tbl2, part4)
tbl2
```
 
# Variant 3 Deaths (for studies collecting death information from public records)
```{r variant 3}
# preprocessing steps
l <- levels(adsl[adsl$dthcat == "OTHER", ]$DTHCAUS)

#table
part1 <- basic_table() %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  add_colcounts() %>%
    count_values("DTHFL", values = "Y", .labels =  c(count_fraction = "Total number of deaths"),
                                   .formats = c(count_fraction = "xx (xx.x%)"))  %>%
  summarize_vars(vars = c("DTHCAT"), var_labels = c("Primary cause of death")) %>%
  build_table(df = adsl)


part2 <- basic_table() %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  add_colcounts() %>%
    split_rows_by("DTHCAT", split_fun = keep_split_levels("OTHER"), child_labels = "hidden") %>%
  count_values("DTHCAUS", values = l[4], .labels = c(count_fraction = "Post study reporting of deaths"),
                                   .formats = c(count_fraction = "xx (xx.x%)"),
                                   .indent_mods = c(count_fraction = 4L))  %>%
   count_values("DTHCAUS", values = l[-4], .labels = c(count_fraction = "All other causes"),
                                    .formats = c(count_fraction = "xx (xx.x%)"),
                                    .indent_mods = c(count_fraction = 4L))  %>%
  build_table(adsl)


col_info(part2) <- col_info(part1)
tbl3 <- rbind(part1, part2)
tbl3

```

# Variant 4 Deaths (adding details for "All other causes" category for studies collecting death information from public records)

```{r variant 4}
#preprocessing steps
l <- levels(adsl[adsl$dthcat == "OTHER", ]$DTHCAUS)
adsl <- adsl %>%
  mutate(DTHCAUS_other = ifelse(
    DTHCAT == "OTHER" & DTHCAUS != "Post-study reporting of death",
    as.character(DTHCAUS), NA)
  )
adsl$dthcaus_other <- as.factor(adsl$dthcaus_other)

#table
part1 <- basic_table() %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  add_colcounts() %>%
    count_values("DTHFL", values = "Y", .labels =  c(count_fraction = "Total number of deaths"),
                                   .formats = c(count_fraction = "xx (xx.x%)"))  %>%
  summarize_vars(vars = c("DTHCAT"), var_labels = c("Primary cause of death")) %>%
  build_table(df = adsl)


part2 <- basic_table() %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  add_colcounts() %>%
    split_rows_by("DTHCAT", split_fun = keep_split_levels("OTHER"), child_labels = "hidden") %>%
  count_values("DTHCAUS", values = l[4], .labels = c(count_fraction = "Post study reporting of deaths"),
                                   .formats = c(count_fraction = "xx (xx.x%)"),
                                   .indent_mods = c(count_fraction = 4L))  %>%
   count_values("DTHCAUS", values = l[-4], .labels = c(count_fraction = "All other causes"),
                                    .formats = c(count_fraction = "xx (xx.x%)"),
                                    .indent_mods = c(count_fraction = 4L))  %>%
  build_table(adsl)

part3 <- basic_table() %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  add_colcounts() %>%
  split_rows_by("DTHCAT", split_fun = keep_split_levels("OTHER"), child_labels = "hidden") %>%
  summarize_vars("DTHCAUS_other", nested = T, .stats = "count_fraction", .indent_mods = c("count_fraction" = 6L)) %>%
  build_table(df = adsl)

col_info(part2) <- col_info(part1)
col_info(part3) <- col_info(part2)

tbl4 <- rbind(part1, part2)
tbl4 <- rbind(tbl4, part3)
tbl4
```
