---
title: "Design for LBT05"
author: "Imanol Zubizarreta"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    theme: journal
    highlight: zenburn
vignette: >
  %\VignetteIndexEntry{Design of LBT05}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svg"
)
```

## Configuration

```{r setup}
library(rtables)
library(tern)
library(assertthat)
library(dplyr)

packageVersion("tern")
packageVersion("rtables")
```

## Data for examples

```{r data, results = "asis", eval = TRUE}
adlb <- haven::read_sas(paste0(pth, "adlb.sas7bdat"))
adsl <- haven::read_sas(paste0(pth, "adsl.sas7bdat"))

# Ensure character variables are converted to factors and empty strings and NAs are explicit missing levels.
# For details, refer to Teal and Study Data article.
adsl <- df_explicit_na(adsl)
adlb <- df_explicit_na(adlb)

# Important points for understanding preprocessing steps:
# 1. “single, not last” and “last or replicated” categories should be mutually exclusive. If a patient has
# abonormalities that meet both the "single, not last" and "last or replicated" criteria, then the patient will be
# counted only under the "last or replicated" category.
# Hence, in order the patient not to be considered in "single", when is "last or replicated" we are creating
# AVALCAT1_NUM, and using this variable to later create the final AVALCAT1_FL analysis variable.


adlb_f <-
  adlb %>% filter(ONTRTFL == "Y" &
                    PARCAT2 == "LS" & SAFFL == "Y" & !is.na(AVAL)) %>%
  mutate(
    DIRECTION = case_when(
      ANRIND %in% c("LOW LOW") ~ "LL",
      ANRIND %in% c("HIGH HIGH") ~ "HH",
      TRUE ~ "<Missing>"
    ),
    AVALCAT1_NUM = case_when(
      AVALCAT1 == "SINGLE" ~ 1,
      AVALCAT1 == "REPLICATED" ~ 2,
      AVALCAT1 == "LAST" ~ 3,
      TRUE ~ 0
    )
  ) %>%
  group_by(USUBJID, PARAMCD, DIRECTION) %>%
  mutate(MAX_AVALCAT1 = max(AVALCAT1_NUM)) %>%
  ungroup() %>%
  mutate(
    AVALCAT1_NUM = ifelse(AVALCAT1_NUM == 1 &
                            AVALCAT1_NUM < MAX_AVALCAT1, 0, AVALCAT1_NUM),
    AVALCAT1_FL = case_when(
      AVALCAT1_NUM == 1 ~ "Single, not last",
      AVALCAT1_NUM == 2 ~ "Last or replicated",
      AVALCAT1_NUM == 3 ~ "Last or replicated",
      TRUE ~ "<Missing>"
    )
  )

adsl_f <- adsl %>% filter(SAFFL == "Y")

adsl_f <- df_explicit_na(adsl)
adlb_f <- df_explicit_na(adlb_f)
```

## New Tern function

```{r}
s_count_abnormal_by_marked <- function(df,
                                       .var = "AVALCAT1_FL",
                                       abnormal = c(Low = "low", High = "high"),
                                       variables = list(id = "USUBJID", direction = "DIRECTION")) {

  assertthat::assert_that(
    assertthat::is.string(.var),
    is.list(variables),
    all(names(variables) %in% c("id", "direction")),
    is_df_with_variables(df, c(aval = .var, variables)),
    is_character_or_factor(df[[.var]]),
    is_character_or_factor(df[[variables$id]])
  )
  n <- length(unique(df[[variables$id]]))
  df <- df[df[[.var]] != "<Missing>", ]
  anl <- data.frame(
    id = df[[variables$id]],
    marked = df[[.var]],
    direction = df[[variables$direction]],
    stringsAsFactors = FALSE
  )
  # Denominator is number of patients with at least one valid measurement during treatment
  # Numerator is number of patients with single or replicated abnormalities
  if (abnormal == "low") {
    anl_abn <- anl[anl$direction == "LL", , drop = FALSE]
  } else if (abnormal == "high") {
    anl_abn <- anl[anl$direction == "HH", , drop = FALSE]
  }
  frequencies <- setNames(c("Single, not last", "Last or replicated"), c("Single, not last", "Last or replicated"))
  by_marked <- lapply(frequencies, function(i) {
    num <- length(unique(anl_abn[anl_abn$marked == i, "id", drop = TRUE]))
    fraction <- ifelse(n == 0, 0, num / n)
    c(num, fraction)
  })
  # Numerator for "Any" grade is number of patients with at least one single/replicated abnormality
  any_marked_num <- ifelse(n == 0, 0, length(unique(anl_abn$id)))
  any_marked_fraction <- ifelse(n == 0, 0, any_marked_num / n)

  list(count_fraction = c(by_marked, list("Any" = c(any_marked_num, any_marked_fraction))))
}



a_count_abnormal_by_marked <- make_afun(  #nolint
  s_count_abnormal_by_marked,
  .formats = c(count_fraction = format_count_fraction)
)



count_abnormal_by_marked <- function(lyt,
                                     var,
                                     abnormal,
                                     variables,
                                     ...,
                                     table_names = abnormal,
                                     .stats = NULL,
                                     .formats = NULL,
                                     .labels = NULL,
                                     .indent_mods = NULL) {
  assertthat::assert_that(
    assertthat::is.string(var),
    !is.null(names(abnormal)),
    is_equal_length(abnormal, table_names)
  )
  afun <- make_afun(
    a_count_abnormal_by_marked,
    .stats = .stats,
    .formats = .formats,
    .labels = .labels,
    .indent_mods = .indent_mods,
    .ungroup_stats = "count_fraction"
  )
  for (i in seq_along(abnormal)) {
    abn <- abnormal[i]
    varlist <- variables
    lyt <- analyze(
      lyt = lyt,
      vars = var,
      var_labels = names(abn),
      table_names = table_names[i],
      afun = afun,
      extra_args = c(list(abnormal = abn, variables = varlist, list(...))),
      show_labels = "visible"
    )
  }
  lyt
}


```


## Full LBT05 Example
```{r}
# Define the split function
split_fun <- drop_split_levels

lyt <- basic_table() %>%
  split_cols_by("ACTARMCD") %>%
  add_colcounts() %>%
  split_rows_by("PARAM", split_fun = split_fun) %>%
  summarize_num_patients(var = "USUBJID",
                         .stats = "unique_count") %>%
  count_abnormal_by_marked(var = "AVALCAT1_FL",
                              abnormal = c(Low = "low", High = "high"),
                              variables = list(id = "USUBJID", direction = "DIRECTION"))

result <- build_table(lyt, df = adlb_f, alt_counts_df = adsl_f)
result
```
