---
title: 'Design: Individual plots of concentrations vs. time (over laid by cohort/TRT) (PKCG02)'
author: "Qi Liu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Design of DORT01}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svg"
)
```

## Configuration

```{r setup}
library(rtables)
library(tern)
library(dplyr)
library(scda.2021)
packageVersion("tern")
packageVersion("rtables")


```

# Variant 1

Individual plots of concentrations vs. time (Over laid by Treatment)

```{r variant1, results = "asis", eval = TRUE}

adpc <- synthetic_cdisc_data("latest")$adpc

adpc_a <- adpc %>% 
  filter(
    PARAM =="Plasma Drug X",
    ARMCD == "ARM A"
    ) %>% 
  mutate(Patient_ID = sub(".*id-", "", USUBJID)) %>% 
  filter(Patient_ID %in% unique(Patient_ID)[1:20])

result <- g_ipp(
  df = adpc_a,
  xvar = "NRELTM1",
  yvar = "AVAL",
  xlab = "Norminal Time from First Dose (hr)",
  ylab = "Concentration (ug/mL)",
  id_var = "Patient_ID",
  add_baseline_hline = F,
  yvar_baseline = "AVAL",  #  yvar_baseline cannot be NA or ignore
  title = "Individual X Concentration (ug/mL) Over Time by Treatment",
  subtitle = "Treatment Arm A", # how to add second line of subtitle
  plotting_choices = "all_in_one" # line style
)
result


```


