#' Generate PK reference dataset
#' @describeIn Generates a dataframe of the correct order of the PK parameters
#' @return dataframe of PK parameters
#' @export
#'
#' @examples
#' pk_reference_dataset <- d_pkparam()
d_pkparam <- function() {
  pk_dataset <- as.data.frame(matrix(c(
    "TMAX", "Time of CMAX", "Tmax", "Plasma/Blood/Serum", "1",
    "CMAX", "Max Conc", "Cmax", "Plasma/Blood/Serum", "2",
    "CMAXD", "Max Conc Norm by Dose", "Cmax/D", "Plasma/Blood/Serum", "3",
    "AUCIFO", "AUC Infinity Obs", "AUCinf obs", "Plasma/Blood/Serum", "4",
    "AUCIFP", "AUC Infinity Pred", "AUCinf pred", "Plasma/Blood/Serum", "5",
    "AUCIFOD", "AUC Infinity Obs Norm by Dose", "AUCinf/D obs", "Plasma/Blood/Serum", "6",
    "AUCIFD", "AUC Infinity Pred Norm by Dose", "AUCinf/D pred", "Plasma/Blood/Serum", "7",
    "AUCPEO", "AUC %Extrapolation Obs", "AUCinf extrap obs", "Plasma/Blood/Serum", "8",
    "AUCPEP", "AUC %Extrapolation Pred", "AUCinf extrap pred", "Plasma/Blood/Serum", "9",
    "AUCINT", "AUC from T1 to T2", "AUCupper-lower ", "Plasma/Blood/Serum", "10",
    "AUCTAU", "AUC Over Dosing Interval", "AUCtau", "Plasma/Blood/Serum", "11",
    "AUCLST", "AUC to Last Nonzero Conc", "AUClast", "Plasma/Blood/Serum", "12",
    "AUCALL", "AUC All", "AUCall", "Plasma/Blood/Serum", "13",
    "AUMCIFO", "AUMC Infinity Obs", "AUMCinf obs", "Plasma/Blood/Serum", "14",
    "AUMCIFP", "AUMC Infinity Pred", "AUMCinf pred", "Plasma/Blood/Serum", "15",
    "AUMCPEO", "AUMC % Extrapolation Obs", "AUMC extrap obs", "Plasma/Blood/Serum", "16",
    "AUMCPEP", "AUMC % Extrapolation Pred", "AUMC extrap pred", "Plasma/Blood/Serum", "17",
    "AUMCTAU", "AUMC Over Dosing Interval", "AUMCtau", "Plasma/Blood/Serum", "18",
    "AUMCLST", "AUMC to Last Nonzero Conc", "AUMClast", "Plasma/Blood/Serum", "19",
    "AURCIFO", "AURC Infinity Obs", "AURCinf obs", "Plasma/Blood/Serum", "20",
    "AURCIFP", "AURC Infinity Pred", "AURCinf pred", "Plasma/Blood/Serum", "21",
    "AURCPEO", "AURC % Extrapolation Obs", "AURC extrap obs", "Plasma/Blood/Serum", "22",
    "AURCPEP", "AURC % Extrapolation Pred", "AURC extrap pred", "Plasma/Blood/Serum", "23",
    "AURCLST", "AURC Dosing to Last Conc", "AURCIast", "Plasma/Blood/Serum", "24",
    "AURCALL", "AURC All", "AURCall", "Plasma/Blood/Serum", "25",
    "TLST", "Time of Last Nonzero Conc", "Tlast", "Plasma/Blood/Serum", "26",
    "CO", "Initial Conc", "CO", "Plasma/Blood/Serum", "27",
    "CAVG", "Average Conc", "Cavg", "Plasma/Blood/Serum", "28",
    "CLST", "Last Nonzero Conc", "Clast", "Plasma/Blood/Serum", "29",
    "CMIN", "Min Conc", "Cmin", "Plasma/Blood/Serum", "30",
    "LAMZHL", "Half-Life Lambda z", "t1/2", "Plasma/Blood/Serum", "31",
    "CLFO", "Total CL Obs by F", "CL/F obs", "Plasma/Blood/Serum", "32",
    "CLFP", "Total CL Pred by F", "CL/F pred", "Plasma/Blood/Serum", "33",
    "CLO", "Total CL Obs", "CL obs", "Plasma/Blood/Serum", "34",
    "CLP", "Total CL Pred", "CL pred", "Plasma/Blood/Serum", "35",
    "CLSS", "Total CL Steady State Pred", "CLss", "Plasma/Blood/Serum", "36",
    "CLSSF", "Total CL Steady State Pred by F", "CLss/F", "Plasma/Blood/Serum", "37",
    "VZFO", "Vz Obs by F", "Vz/F obs", "Plasma/Blood/Serum", "38",
    "VZFP", "Vz Pred by F", "Vz/F pred", "Plasma/Blood/Serum", "39",
    "VZO", "Vz Obs", "Vz obs", "Plasma/Blood/Serum", "40",
    "VZP", "Vz Pred", "Vz pred", "Plasma/Blood/Serum", "41",
    "VSSO", "Vol Dist Steady State Obs", "Vss obs", "Plasma/Blood/Serum", "42",
    "VSSP", "Vol Dist Steady State Pred", "Vss pred", "Plasma/Blood/Serum", "43",
    "LAMZ", "Lambda z", "Lambda z", "Plasma/Blood/Serum", "44",
    "LAMZLL", "Lambda z Lower Limit", "Lambda z lower", "Plasma/Blood/Serum", "45",
    "LAMZUL", "Lambda z Upper Limit", "Lambda z upper", "Plasma/Blood/Serum", "46",
    "LAMZNPT", "Number of Points for Lambda z", "No points Lambda z", "Plasma/Blood/Serum", "47",
    "MRTIFO", "MRT Infinity Obs", "MRTinf obs", "Plasma/Blood/Serum", "48",
    "MRTIFP", "MRT Infinity Pred", "MRTinf pred", "Plasma/Blood/Serum", "49",
    "MRTLST", "MRT to Last Nonzero Conc", "MRTlast", "Plasma/Blood/Serum", "50",
    "R2", "R Squared", "Rsq", "Plasma/Blood/Serum", "51",
    "R2ADJ", "R Squared Adjusted", "Rsq adjusted", "Plasma/Blood/Serum", "52",
    "TLAG", "Time Until First Nonzero Conc", "TIag", "Plasma/Blood/Serum", "53",
    "TMIN", "Time of CMIN Observation", "Tmin", "Plasma/Blood/Serum", "54",
    "ACCI", "Accumulation Index", "Accumulation Index", "Plasma/Blood/Serum/Urine", "55",
    "FLUCP", "Fluctuation%", "Fluctuation", "Plasma/Blood/Serum", "56",
    "CORRXY", "Correlation Between TimeX and Log ConcY", "Corr xy", "Plasma/Blood/Serum", "57",
    "RCAMINT", "Amt Rec from T1 to T2", "Ae", "Urine", "58",
    "RCPCINT", "Pct Rec from T1 to T2", "Fe", "Urine", "59",
    "VOLPK", "Sum of Urine Vol", "Urine volume", "Urine", "60",
    "RENALCL", "Renal CL", "CLR", "Plasma/Blood/Serum/Urine", "61",
    "ERTMAX", "Time of Max Excretion Rate", "Tmax Rate", "Urine", "62",
    "RMAX", "Time of Maximum Response", "Rmax", "Matrix of PD", "63",
    "RMIN", "Time of Minimum Response", "Rmin", "Matrix of PD", "64",
    "ERMAX", "Max Excretion Rate", "Max excretion rate", "Urine", "65",
    "MIDPTLST", "Midpoint of Collection Interval", "Midpoint last", "Urine", "66",
    "ERLST", "Last Meas Excretion Rate", "Rate last", "Urine", "67",
    "TON", "Time to Onset", "Tonset", "Matrix of PD", "68",
    "TOFF", "Time to Offset", "Toffset", "Matrix of PD", "69",
    "TBBLP", "Time Below Baseline %", "Time %Below Baseline", "Matrix of PD", "70",
    "TBTP", "Time Below Threshold %", "Time %Below Threshold", "Matrix of PD", "71",
    "TABL", "Time Above Baseline", "Time Above Baseline", "Matrix of PD", "72",
    "TAT", "Time Above Threshold", "Time Above Threshold", "Matrix of PD", "73",
    "TBBLP", "Time Below Baseline", "Time Below Baseline", "Matrix of PD", "74",
    "TBT", "Time Below Threshold", "Time Below Threshold", "Matrix of PD", "75",
    "TBLT", "Time Between Baseline and Threshold", "Time Between Baseline Threshold", "Matrix of PD", "76",
    "BLRSP", "Baseline Response", "Baseline", "Matrix of PD", "77",
    "TSHDRSP", "Response Threshold", "Threshold", "Matrix of PD", "78",
    "AUCABL", "AUC Above Baseline", "AUC above baseline", "Matrix of PD", "79",
    "AUCAT", "AUC Above Threshold", "AUC above threshold", "Matrix of PD", "80",
    "AUCBBL", "AUC Below Baseline", "AUC below baseline", "Matrix of PD", "81",
    "AUCBT", "AUC Below Threshold", "AUC be low threshold", "Matrix of PD", "82",
    "AUCBLDIF", "Diff AUC Above Base and AUC Below Base", "AUC diff baseline", "Matrix of PD", "83",
    "AUCTDIF", "Diff AUC Above Thr and AUC Below Thr", "AUCnet threshold", "Matrix of PD", "84",
    "TDIFF", "Diff Time to Offset and Time to Onset", "Diff toffset-tonset", "Matrix of PD", "85",
    "AUCPBEO", "AUC %Back Extrapolation Obs", "AUC%Back extrap obs", "Plasma/Blood/Serum", "86",
    "AUCPBEP", "AUC %Back Extrapolation Pred", "AUC%Back extrap pred", "Plasma/Blood/Serum", "87",
    "TSLP1L", "Lower Time Limit Slope 1st", "Slope1 lower", "Matrix of PD", "88",
    "TSLP1U", "Upper Time Limit Slope 1st Segment", "Slope1 upper", "Matrix of PD", "89",
    "TSLP2L", "Lower Time Limit Slope 2nd Segment", "Slope2 lower", "Matrix of PD", "90",
    "TSLP2U", "Upper Time Limit Slope 2nd Segment", "Slope2 upper", "Matrix of PD", "91",
    "SLP1", "Slope, 1st Segment", "Slope1", "Matrix of PD", "92",
    "SLP2", "Slope, 2nd Segment", "Slope2", "Matrix of PD", "93",
    "SLP1PT", "Number of Points for Slope 1st Segment", "No points slope1", "Matrix of PD", "94",
    "SLP2PT", "Number of Points for Slope 2nd Segment", "No points slope2", "Matrix of PD", "95",
    "R2ADJS1", "R-Squared Adjusted Slope, 1st Segment", "Rsg adjusted slope1", "Matrix of PD", "96",
    "R2ADJS2", "R-Squared Adjusted Slope, 2nd Segment", "Rsq adjusted slope2", "Matrix of PD", "97",
    "R2SLP1", "R Squared, Slope, 1st Segment", "Rsq slope1", "Matrix of PD", "98",
    "R2SLP2", "R Squared, Slope, 2nd Segment", "Rsq slope2", "Matrix of PD", "99",
    "CORRXYS1", "Corr Btw TimeX and Log ConcY, Slope 1st", "Corr xy slope 1", "Plasma/Blood/Serum", "100",
    "CORRXYS2", "Corr Btw TimeX and Log ConcY, Slope 1st Slope 2nd", "Corr xy slope2", "Plasma/Blood/Serum", "101"
  ),
  ncol = 5,
  byrow = TRUE
  ))
  colnames(pk_dataset) <- c("PARM", "PPTEST", "TLG display", "Matrix", "TLG Order")
  pk_dataset
}
