---
name: Docs 📚

on:
  push:
    branches:
      - main
    paths:
      - "inst/templates/**"
      - "_pkgdown.*"
      - DESCRIPTION
      - "**.md"
      - "**.Rmd"
      - "man/**"
      - "LICENSE.*"
      - NAMESPACE
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
    paths:
      - "inst/templates/**"
      - "_pkgdown.*"
      - DESCRIPTION
      - "**.md"
      - "**.Rmd"
      - "man/**"
      - "LICENSE.*"
      - NAMESPACE
  workflow_dispatch:

jobs:
  docs:
    name: Pkgdown Docs 📚
    uses: insightsengineering/r.pkg.template/.github/workflows/pkgdown.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      deps-installation-method: setup-r-dependencies
      lookup-refs: |
        insightsengineering/nestcolor
        insightsengineering/formatters
        insightsengineering/rtables
      default-landing-page: latest-tag
      additional-unit-test-report-directories: unit-test-report-non-cran
