---
name: revdepcheck ⏪

on:
  schedule:
    - cron: '45 3 * * 0'
  push:
    branches:
      - initialize-revdepcheck-action
  workflow_dispatch:


jobs:
  revdepcheck:
    name: revdepcheck ↩️
    uses: insightsengineering/r.pkg.template/.github/workflows/revdepcheck.yaml@initialize-revdepcheck-action
